version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - run: javac HelloWorld.java
  test:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - run: java HelloWorld
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test