version: 2
jobs:
  build:
    docker:
      - image: opensourcecobol/opensource-cobol
    steps:
      - checkout
      - run: cobc HELLO.cbl
  test:
    docker:
      - image: opensourcecobol/opensource-cobol
    steps:
      - checkout
      - run: cobc -m -o HELLO.so HELLO.cbl
      - run: cobcrun HELLO
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
